compressionLevel: 0Add commentMore actions
enableGlobalCache: true
enableScripts: false
enableTelemetry: false
logFilters:
  - code: YN0013
    level: discard
nmMode: hardlinks-local
nodeLinker: node-modules
